import * as dotenv from "dotenv"
dotenv.config()

export const enum Errors {
	UNKNOWN = "UNKNOWN",
	INVALID_INPUT = "INVALID INPUT",
	DUPLICATED_RECORD = "DUPLICATED RECORD",
	RECORD_NOT_FOUND = "RECORD NOT FOUND",
	BAD_AUTHENTICATION = "BAD AUTHENTICATION",
	AUTH_TOKEN_NOT_FOUND = "AUTH TOKEN NOT FOUND",
	INVALID_AUTH_TOKEN = "INVALID AUTH TOKEN",
	UNAUTHORIZED = "UNAUTHORIZED"
}

export const enum Responses {
	OK = 200,
	CREATED = 201,
	BAD_REQUEST = 400,
	UNAUTHORIZED = 401,
	FORBIDDEN = 403,
	NOT_FOUND = 404,
	METHOD_NOT_ALLOWED = 405,
	CONFLICT = 409,
	INTERNAL_SERVER_ERROR = 500,
	SERVICE_UNAVAILABLE = 503
}

export const {
	DEBUG,
	MAX_LOGS_CHARS,
	SERVER_SSL_KEY_PATH,
	SERVER_SSL_CERTIFICATE_PATH,
	SERVER_PORT,
	JWT_CODE_EXPIRATION,
	SECRET_JWT_CODE,
	WEB_APP_URL,
	EMAIL_SERVER,
	EMAIL_SERVER_PORT,
	EMAIL_USER,
	EMAIL_PASS,
	PROJECT_NAME,
	FORGOT_PASSWORD_NOREPLY_EMAIL,
	DATABASE_URI,
	BASIC_AUTH_USER,
	BASIC_AUTH_PASS
} = process.env
